server.port=${SERVER_PORT:8088}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/budou}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

rocketmq.name-server=${ROCKETMQ_NAME_SERVER:127.0.0.1:9876}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:127.0.0.1}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME:}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
