server.port=8088

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/budou
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

rocketmq.name-server=127.0.0.1:9876
rocketmq.producer.group=test
rocketmq.consumer.group=test_consumer
rocketmq.topic=TestTopic
rocketmq.consumer.max-retry-times=3
rocketmq.dead-letter-consumer.group=dead_letter_consumer
rocketmq.dead-letter-consumer.topic=%DLQ%test_consumer

#log4j.rootLogger=INFO, stdout
#log4j.appender.stdout=org.apache.log4j.ConsoleAppender
#log4j.appender.stdout.Target=System.out
#log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#log4j.appender.stdout.layout.ConversionPattern=%d{MM/dd/yyyy HH:mm:ss} %-5p %c{1}:%L - %m%n

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=5000
spring.data.redis.lettuce.pool.max-active=32
spring.data.redis.lettuce.pool.max-wait= -1
spring.data.redis.lettuce.pool.max-idle= 16
spring.data.redis.lettuce.pool.min-idle= 8

spring.cloud.sentinel.transport.dashboard=localhost:8081
spring.cloud.sentinel.transport.port=8719




